### ISSUE TITLE
Xstream addon from this repo

### ISSUE THREAD

**Issue by u040201** [Mastaaa1987/Mastaaa1987.github.io#1]
The xstream addon from this repo will install malware. The bug is in default.py

**Comment by Mastaaa1987** [comment]
Für default.py ist from the offiziell GitHub repo, this files are all decoded... Why you think its malware?

**Comment by u040201** [comment]
Because of this
[image0.jpeg]

Mein ipad

Am 04.10.2024 um 11:39 schrieb Mastaaa ***@***.***>:

﻿

Für default.py ist from the offiziell GitHub repo, this files are all decoded... Why you think its malware?

**Comment by Mastaaa1987** [comment]
Digga wenn du deutsch kannst lass ma deutsch sprechen ....
Kann es sein das beim bild hochladen was schief gelaufen ist? Ich sehe nur den Namen vom Bild aber das bild ansich nicht ...

**Comment by Mastaaa1987** [comment]
Also das xstream addon hab ich von hier https://github.com/streamxstream/xStreamRepo Deshalb weiß ich jetzt auch nicht wie du da auf malware kommst , zeig doch bitte nochmal das bild damit kann ich wahrscheinlich mehr anfangen

**Comment by u040201** [comment]
[image0.jpeg]

Mein ipad

Am 04.10.2024 um 22:24 schrieb Mastaaa ***@***.***>:

﻿

Also das xstream addon hab ich von hier https://github.com/streamxstream/xStreamRepo Deshalb weiß ich jetzt auch nicht wie du da auf malware kommst , zeig doch bitte nochmal das bild damit kann ich wahrscheinlich mehr anfangen

**Comment by Mastaaa1987** [comment]
Digga Es ist immer noch kein Bild zu sehen, nur der name "image0.jpeg" ... Haste kein Telegram oder so? Das wird ja so sonst nix -.-

**Comment by u040201** [comment]
Mein ipad

Am 05.10.2024 um 09:30 schrieb Mastaaa ***@***.***>:

﻿

Digga Es ist immer noch kein Bild zu sehen, nur der name "image0.jpeg" ... Haste kein Telegram oder so? Das wird ja so sonst nix -.-

**Comment by Mastaaa1987** [comment]
Was dein ipad? kannst du mal in ganzen sätzen sprechen oder is das zu viel verlangt für dich und dein ipad?

**Comment by Mastaaa1987** [comment]
Und wieso Forkst du eigentlich mein repo bist du nur dumm oder was soll das bitte für einen sinn haben?

**Comment by u040201** [comment]
Nothing forked. Picture sent.

Mein ipad

Am 05.10.2024 um 13:17 schrieb Mastaaa ***@***.***>:

﻿

Und wieso Forkst du eigentlich mein repo bist du nur dumm oder was soll das bitte für einen sinn haben?

**Comment by Mastaaa1987** [comment]
Men I am so confused ...
Can you speak German, yes or not?
And where is the picture, what you say? I can't see a Picture, only the name of it! but no Picture ... Can you upload the Picture anywhere else, plz?

**Comment by Mastaaa1987** [comment]
Do you have Telegram? Or Whatsapp maybe?

**Comment by AtzeTh83** [comment]
Guten Morgen, ich klinke mich mal hier ein 😉 Ich wollte mal fragen ob es noch eine Möglichkeit an deinen VXParser unter Termux zu kommen ? LG

**Comment by Mastaaa1987** [comment]
Nein
